# python
#2013-04-20

#Project Euler - Problem 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

#answer: 4613732

eventotal = 0
terms = [0,1]   # given by definition
i = 2           # start at the 2nd term, since 0th and 1st are defined.
newterm = 0
while newterm <= 4000000:     # make the list just long enough to reach nth term.
    newterm = terms[i-1] + terms[i-2]
    terms.append(newterm)     # each new appended element (ith), is the sum of the prior 2 terms
    if newterm%2 == 0:                      # is newterm even?
        eventotal = eventotal + newterm     # add any even newterm to eventotal's running total
    i = i + 1                               # go to next item in list
print eventotal                           # list now has n terms, now pull the value.
